// 全球主要货币（ISO 4217）列表与兜底汇率。
// 实时汇率由后端 /api/fx/rates 提供（USD 基准），这里只在实时汇率不可用时兜底。

export interface CurrencyInfo {
  code: string;
  name: string;
  symbol: string;
}

export const CURRENCIES: CurrencyInfo[] = [
  { code: 'USD', name: 'US Dollar 美元', symbol: '$' },
  { code: 'CNY', name: 'Chinese Yuan 人民币', symbol: '¥' },
  { code: 'EUR', name: 'Euro 欧元', symbol: '€' },
  { code: 'JPY', name: 'Japanese Yen 日元', symbol: '¥' },
  { code: 'GBP', name: 'British Pound 英镑', symbol: '£' },
  { code: 'HKD', name: 'Hong Kong Dollar 港币', symbol: 'HK$' },
  { code: 'TWD', name: 'New Taiwan Dollar 新台币', symbol: 'NT$' },
  { code: 'MOP', name: 'Macanese Pataca 澳门元', symbol: 'MOP$' },
  { code: 'KRW', name: 'South Korean Won 韩元', symbol: '₩' },
  { code: 'SGD', name: 'Singapore Dollar 新加坡元', symbol: 'S$' },
  { code: 'MYR', name: 'Malaysian Ringgit 林吉特', symbol: 'RM' },
  { code: 'THB', name: 'Thai Baht 泰铢', symbol: '฿' },
  { code: 'VND', name: 'Vietnamese Dong 越南盾', symbol: '₫' },
  { code: 'PHP', name: 'Philippine Peso 菲律宾比索', symbol: '₱' },
  { code: 'IDR', name: 'Indonesian Rupiah 印尼盾', symbol: 'Rp' },
  { code: 'INR', name: 'Indian Rupee 印度卢比', symbol: '₹' },
  { code: 'PKR', name: 'Pakistani Rupee 巴基斯坦卢比', symbol: '₨' },
  { code: 'BDT', name: 'Bangladeshi Taka 塔卡', symbol: '৳' },
  { code: 'LKR', name: 'Sri Lankan Rupee 斯里兰卡卢比', symbol: '₨' },
  { code: 'NPR', name: 'Nepalese Rupee 尼泊尔卢比', symbol: '₨' },
  { code: 'KHR', name: 'Cambodian Riel 瑞尔', symbol: '៛' },
  { code: 'LAK', name: 'Lao Kip 基普', symbol: '₭' },
  { code: 'MMK', name: 'Myanmar Kyat 缅甸元', symbol: 'K' },
  { code: 'BND', name: 'Brunei Dollar 文莱元', symbol: 'B$' },
  { code: 'MNT', name: 'Mongolian Tugrik 图格里克', symbol: '₮' },
  { code: 'KZT', name: 'Kazakhstani Tenge 坚戈', symbol: '₸' },
  { code: 'AUD', name: 'Australian Dollar 澳元', symbol: 'A$' },
  { code: 'NZD', name: 'New Zealand Dollar 新西兰元', symbol: 'NZ$' },
  { code: 'CAD', name: 'Canadian Dollar 加元', symbol: 'C$' },
  { code: 'CHF', name: 'Swiss Franc 瑞士法郎', symbol: 'CHF' },
  { code: 'SEK', name: 'Swedish Krona 瑞典克朗', symbol: 'kr' },
  { code: 'NOK', name: 'Norwegian Krone 挪威克朗', symbol: 'kr' },
  { code: 'DKK', name: 'Danish Krone 丹麦克朗', symbol: 'kr' },
  { code: 'ISK', name: 'Icelandic Krona 冰岛克朗', symbol: 'kr' },
  { code: 'PLN', name: 'Polish Zloty 兹罗提', symbol: 'zł' },
  { code: 'CZK', name: 'Czech Koruna 捷克克朗', symbol: 'Kč' },
  { code: 'HUF', name: 'Hungarian Forint 福林', symbol: 'Ft' },
  { code: 'RON', name: 'Romanian Leu 列伊', symbol: 'lei' },
  { code: 'BGN', name: 'Bulgarian Lev 列弗', symbol: 'лв' },
  { code: 'RSD', name: 'Serbian Dinar 第纳尔', symbol: 'дин' },
  { code: 'UAH', name: 'Ukrainian Hryvnia 格里夫纳', symbol: '₴' },
  { code: 'RUB', name: 'Russian Ruble 卢布', symbol: '₽' },
  { code: 'TRY', name: 'Turkish Lira 里拉', symbol: '₺' },
  { code: 'ILS', name: 'Israeli Shekel 谢克尔', symbol: '₪' },
  { code: 'AED', name: 'UAE Dirham 迪拉姆', symbol: 'د.إ' },
  { code: 'SAR', name: 'Saudi Riyal 沙特里亚尔', symbol: '﷼' },
  { code: 'QAR', name: 'Qatari Riyal 卡塔尔里亚尔', symbol: '﷼' },
  { code: 'KWD', name: 'Kuwaiti Dinar 第纳尔', symbol: 'د.ك' },
  { code: 'BHD', name: 'Bahraini Dinar 巴林第纳尔', symbol: '.د.ب' },
  { code: 'OMR', name: 'Omani Rial 阿曼里亚尔', symbol: '﷼' },
  { code: 'JOD', name: 'Jordanian Dinar 约旦第纳尔', symbol: 'د.ا' },
  { code: 'EGP', name: 'Egyptian Pound 埃及镑', symbol: 'E£' },
  { code: 'ZAR', name: 'South African Rand 兰特', symbol: 'R' },
  { code: 'NGN', name: 'Nigerian Naira 奈拉', symbol: '₦' },
  { code: 'KES', name: 'Kenyan Shilling 肯尼亚先令', symbol: 'KSh' },
  { code: 'GHS', name: 'Ghanaian Cedi 塞地', symbol: '₵' },
  { code: 'MAD', name: 'Moroccan Dirham 摩洛哥迪拉姆', symbol: 'د.م.' },
  { code: 'DZD', name: 'Algerian Dinar 阿尔及利亚第纳尔', symbol: 'د.ج' },
  { code: 'TND', name: 'Tunisian Dinar 突尼斯第纳尔', symbol: 'د.ت' },
  { code: 'LYD', name: 'Libyan Dinar 利比亚第纳尔', symbol: 'ل.د' },
  { code: 'TZS', name: 'Tanzanian Shilling 坦桑尼亚先令', symbol: 'TSh' },
  { code: 'UGX', name: 'Ugandan Shilling 乌干达先令', symbol: 'USh' },
  { code: 'ETB', name: 'Ethiopian Birr 比尔', symbol: 'Br' },
  { code: 'XOF', name: 'West African CFA Franc 西非法郎', symbol: 'CFA' },
  { code: 'XAF', name: 'Central African CFA Franc 中非法郎', symbol: 'FCFA' },
  { code: 'BRL', name: 'Brazilian Real 雷亚尔', symbol: 'R$' },
  { code: 'MXN', name: 'Mexican Peso 墨西哥比索', symbol: 'Mex$' },
  { code: 'ARS', name: 'Argentine Peso 阿根廷比索', symbol: 'AR$' },
  { code: 'CLP', name: 'Chilean Peso 智利比索', symbol: 'CLP$' },
  { code: 'COP', name: 'Colombian Peso 哥伦比亚比索', symbol: 'COL$' },
  { code: 'PEN', name: 'Peruvian Sol 索尔', symbol: 'S/' },
  { code: 'UYU', name: 'Uruguayan Peso 乌拉圭比索', symbol: '$U' },
  { code: 'BOB', name: 'Bolivian Boliviano 玻利维亚诺', symbol: 'Bs' },
  { code: 'PYG', name: 'Paraguayan Guarani 瓜拉尼', symbol: '₲' },
  { code: 'VES', name: 'Venezuelan Bolívar 玻利瓦尔', symbol: 'Bs.S' },
  { code: 'CRC', name: 'Costa Rican Colón 科朗', symbol: '₡' },
  { code: 'GTQ', name: 'Guatemalan Quetzal 格查尔', symbol: 'Q' },
  { code: 'DOP', name: 'Dominican Peso 多米尼加比索', symbol: 'RD$' },
  { code: 'JMD', name: 'Jamaican Dollar 牙买加元', symbol: 'J$' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar 特多元', symbol: 'TT$' },
  { code: 'BSD', name: 'Bahamian Dollar 巴哈马元', symbol: 'B$' },
  { code: 'BBD', name: 'Barbadian Dollar巴巴多斯元', symbol: 'Bds$' },
  { code: 'PAB', name: 'Panamanian Balboa 巴波亚', symbol: 'B/.' },
  { code: 'HNL', name: 'Honduran Lempira 伦皮拉', symbol: 'L' },
  { code: 'NIO', name: 'Nicaraguan Córdoba 科多巴', symbol: 'C$' },
  { code: 'FJD', name: 'Fijian Dollar 斐济元', symbol: 'FJ$' },
  { code: 'PGK', name: 'Papua New Guinean Kina 基那', symbol: 'K' },
  { code: 'WST', name: 'Samoan Tala 塔拉', symbol: 'WS$' },
  { code: 'TOP', name: 'Tongan Paʻanga 潘加', symbol: 'T$' },
  { code: 'VUV', name: 'Vanuatu Vatu 瓦图', symbol: 'VT' },
  { code: 'SBD', name: 'Solomon Islands Dollar 所罗门群岛元', symbol: 'SI$' },
  { code: 'XCD', name: 'East Caribbean Dollar 东加勒比元', symbol: 'EC$' },
  { code: 'BMD', name: 'Bermudian Dollar 百慕大元', symbol: 'BD$' },
  { code: 'KYD', name: 'Cayman Islands Dollar 开曼元', symbol: 'CI$' },
  { code: 'AWG', name: 'Aruban Florin 阿鲁巴弗罗林', symbol: 'ƒ' },
  { code: 'GEL', name: 'Georgian Lari 拉里', symbol: '₾' },
  { code: 'AMD', name: 'Armenian Dram 德拉姆', symbol: '֏' },
  { code: 'AZN', name: 'Azerbaijani Manat 马纳特', symbol: '₼' },
  { code: 'BYN', name: 'Belarusian Ruble 白俄罗斯卢布', symbol: 'Br' },
  { code: 'MDL', name: 'Moldovan Leu 摩尔多瓦列伊', symbol: 'L' },
  { code: 'ALL', name: 'Albanian Lek 列克', symbol: 'L' },
  { code: 'MKD', name: 'Macedonian Denar 第纳尔', symbol: 'ден' },
  { code: 'BAM', name: 'Bosnia & Herzegovina Convertible Mark 可兑换马克', symbol: 'KM' },
  { code: 'HRK', name: 'Croatian Kuna 库纳', symbol: 'kn' },
  { code: 'UZS', name: 'Uzbekistani Som 苏姆', symbol: "so'm" },
  { code: 'KGS', name: 'Kyrgystani Som 索姆', symbol: 'с' },
  { code: 'TJS', name: 'Tajikistani Somoni 索莫尼', symbol: 'SM' },
  { code: 'TMT', name: 'Turkmenistani Manat 马纳特', symbol: 'm' },
  { code: 'AFN', name: 'Afghan Afghani 阿富汗尼', symbol: '؋' },
  { code: 'IQD', name: 'Iraqi Dinar 伊拉克第纳尔', symbol: 'ع.د' },
  { code: 'LBP', name: 'Lebanese Pound 黎巴嫩镑', symbol: 'ل.ل' },
  { code: 'SYP', name: 'Syrian Pound 叙利亚镑', symbol: '£S' },
  { code: 'YER', name: 'Yemeni Rial 也门里亚尔', symbol: '﷼' },
  { code: 'SDG', name: 'Sudanese Pound 苏丹镑', symbol: 'ج.س.' },
  { code: 'ZMW', name: 'Zambian Kwacha 克瓦查', symbol: 'ZK' },
  { code: 'MWK', name: 'Malawian Kwacha 克瓦查', symbol: 'MK' },
  { code: 'MZN', name: 'Mozambican Metical 梅蒂卡尔', symbol: 'MT' },
  { code: 'BWP', name: 'Botswanan Pula 普拉', symbol: 'P' },
  { code: 'NAD', name: 'Namibian Dollar 纳米比亚元', symbol: 'N$' },
  { code: 'MUR', name: 'Mauritian Rupee 毛里求斯卢比', symbol: '₨' },
  { code: 'SCR', name: 'Seychellois Rupee 塞舌尔卢比', symbol: '₨' },
  { code: 'RWF', name: 'Rwandan Franc 卢旺达法郎', symbol: 'FRw' },
  { code: 'BIF', name: 'Burundian Franc 布隆迪法郎', symbol: 'FBu' },
  { code: 'DJF', name: 'Djiboutian Franc 吉布提法郎', symbol: 'Fdj' },
  { code: 'SOS', name: 'Somali Shilling 索马里先令', symbol: 'Sh' },
  { code: 'SSP', name: 'South Sudanese Pound 南苏丹镑', symbol: '£' },
  { code: 'GMD', name: 'Gambian Dalasi 达拉西', symbol: 'D' },
  { code: 'GNF', name: 'Guinean Franc 几内亚法郎', symbol: 'FG' },
  { code: 'SLL', name: 'Sierra Leonean Leone 利昂', symbol: 'Le' },
  { code: 'LRD', name: 'Liberian Dollar 利比里亚元', symbol: 'L$' },
  { code: 'CVE', name: 'Cape Verdean Escudo 埃斯库多', symbol: '$' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra 多布拉', symbol: 'Db' },
  { code: 'CDF', name: 'Congolese Franc 刚果法郎', symbol: 'FC' },
  { code: 'AOA', name: 'Angolan Kwanza 宽扎', symbol: 'Kz' },
  { code: 'SZL', name: 'Eswatini Lilangeni 里兰吉尼', symbol: 'E' },
  { code: 'LSL', name: 'Lesotho Loti 洛蒂', symbol: 'L' },
  { code: 'MGA', name: 'Malagasy Ariary 阿里亚里', symbol: 'Ar' },
  { code: 'KMF', name: 'Comorian Franc 科摩罗法郎', symbol: 'CF' },
  { code: 'MRU', name: 'Mauritanian Ouguiya 乌吉亚', symbol: 'UM' },
  { code: 'ERN', name: 'Eritrean Nakfa 纳克法', symbol: 'Nfk' },
  { code: 'XPF', name: 'CFP Franc 太平洋法郎', symbol: '₣' },
  { code: 'FKP', name: 'Falkland Islands Pound 福克兰镑', symbol: '£' },
  { code: 'GIP', name: 'Gibraltar Pound 直布罗陀镑', symbol: '£' },
  { code: 'SHP', name: 'Saint Helena Pound 圣赫勒拿镑', symbol: '£' },
  { code: 'JEP', name: 'Jersey Pound 泽西镑', symbol: '£' },
  { code: 'GGP', name: 'Guernsey Pound 根西镑', symbol: '£' },
  { code: 'IMP', name: 'Isle of Man Pound 马恩岛镑', symbol: '£' },
  { code: 'CUC', name: 'Cuban Convertible Peso 古巴可兑换比索', symbol: '$' },
  { code: 'CUP', name: 'Cuban Peso 古巴比索', symbol: '$MN' },
  { code: 'HTG', name: 'Haitian Gourde 古德', symbol: 'G' },
  { code: 'KPW', name: 'North Korean Won 朝鲜圆', symbol: '₩' },
  { code: 'BTN', name: 'Bhutanese Ngultrum 努尔特鲁姆', symbol: 'Nu.' },
  { code: 'MVR', name: 'Maldivian Rufiyaa 拉菲亚', symbol: 'Rf' },
  { code: 'FOK', name: 'Faroese Króna 法罗克朗', symbol: 'kr' },
];

// 按代码去重并排序
export const ACTIVE_CURRENCIES: CurrencyInfo[] = CURRENCIES.filter(
  (c, index, arr) => arr.findIndex((x) => x.code === c.code) === index
).sort((a, b) => a.code.localeCompare(b.code));

export const CURRENCY_SYMBOLS: Record<string, string> = Object.fromEntries(
  ACTIVE_CURRENCIES.map((c) => [c.code, c.symbol])
);

export const getCurrencySymbol = (code: string): string => CURRENCY_SYMBOLS[code] || code;

// 实时汇率不可用时的近似兜底汇率（USD 基准，仅用于界面参考换算）
export const FALLBACK_RATES: Record<string, number> = {
  USD: 1, CNY: 7.2, EUR: 0.92, JPY: 150, GBP: 0.79, HKD: 7.8, TWD: 32, MOP: 8.03,
  KRW: 1350, SGD: 1.34, MYR: 4.7, THB: 35, VND: 24500, PHP: 56, IDR: 15800,
  INR: 83, PKR: 278, BDT: 110, LKR: 320, NPR: 133, KHR: 4100, LAK: 21000, MMK: 2100,
  BND: 1.34, MNT: 3400, KZT: 450, AUD: 1.5, NZD: 1.64, CAD: 1.36, CHF: 0.88,
  SEK: 10.5, NOK: 10.6, DKK: 6.9, ISK: 138, PLN: 4.0, CZK: 23, HUF: 360, RON: 4.6,
  BGN: 1.8, RSD: 108, UAH: 39, RUB: 92, TRY: 32, ILS: 3.7, AED: 3.67, SAR: 3.75,
  QAR: 3.64, KWD: 0.31, BHD: 0.38, OMR: 0.38, JOD: 0.71, EGP: 31, ZAR: 18.7,
  NGN: 800, KES: 145, GHS: 12, MAD: 10, BRL: 5.0, MXN: 17, ARS: 350, CLP: 900,
  COP: 4000, PEN: 3.7, UYU: 39, AZN: 1.7, GEL: 2.65, AMD: 405, BYN: 3.3, UZS: 12500,
};

export const DEFAULT_CURRENCY = 'USD';
